#!/usr/bin/with-contenv sh

echo "$( date +'%Y/%m/%d %H:%M:%S' ) Mounting ro: ${LOWER_DIR} + rw: ${UPPER_DIR} with workdir: ${WORK_DIR} as ${MERGED_DIR}"

exec sh -c '/usr/local/bin/fuse-overlayfs -o lowerdir=${LOWER_DIR},upperdir=${UPPER_DIR},workdir=${WORK_DIR} ${MERGED_DIR}; \
while true;do sleep 1000;done'
